version: 2

models:
  - name: int_payments_joined_chargeback
    description: Intermediate model for joining chargeback`s transactions information with acceptance`s transactions model
    columns:
      - name: external_ref
        description: Transaction ID
      - name: ref
        description: TBD
      - name: transaction_timestamp
        description: The timestamp of the transaction in the format YYYY-MM-DDTHH:MM:SS.FFFFZ
      - name: transaction_date
        description: The date of the transaction in the format YYYY-MM-DDT00:00:00.000Z
      - name: state
        description: The state of the transaction. For example, Accepted or Declined
      - name: is_cvv_provided
        description: Binary information if the card's CVV was provided.For example, True or False
      - name: amount_usd
        description: The amount that has been charged from the card in USD currency
      - name: country
        description: The two-character ISO country code of the card
      - name: currency
        description: The three-character ISO currency code
      - name: amount_currency
        description: The amount that has been charged from the card in the local currency
      - name: is_chargeback
        description: Binary information if the transaction was chargedback.For example, True or False 
        tests:
              - dbt_utils.not_null_proportion:
                  at_least: 0.95 
      - name: rate_aud
        description: The exchange rate for AUD currency  
      - name: rate_cad
        description: The exchange rate for CAD currency    
      - name: rate_eur
        description: The exchange rate for EUR currency    
      - name: rate_gbp
        description: The exchange rate for GBP currency    
      - name: rate_mxn
        description: The exchange rate for MXN currency  
      - name: rate_sgd
        description: The exchange rate for SGD currency  
      - name: rate_usd
        description: The exchange rate for USD currency                            
