version: 2

models:
  - name: int_payments_joined_chargeback
    description: TBD
    columns:
      - name: external_ref
        description: TBD
      - name: ref
        description: TBD
      - name: transaction_timestamp
        description: TBD
      - name: transaction_date
        description: TBD
      - name: state
        description: TBD
      - name: is_cvv_provided
        description: TBD
      - name: amount_usd
        description: TBD
      - name: country
        description: TBD
      - name: currency
        description: TBD
      - name: amount_currency
        description: TBD
      - name: is_chargeback
        description: TBD 
        tests:
              - dbt_utils.not_null_proportion:
                  at_least: 0.95 
      - name: rate_aud
        description: TBD  
      - name: rate_cad
        description: TBD  
      - name: rate_eur
        description: TBD  
      - name: rate_gbp
        description: TBD  
      - name: rate_mxn
        description: TBD
      - name: rate_sgd
        description: TBD
      - name: rate_usd
        description: TBD                          
